conversions:
  - input: path/to/input_model.bin
    output: path/to/output_model.gguf
    to: gguf
    quant: q4
    model_type: auto
    device: auto
  - input: path/to/input_model2.bin
    output: path/to/output_model2.onnx
    to: onnx
    model_type: bert
    device: cpu