# Example batch conversion configuration
models:
  - model_path: path/to/input_model.bin
    output_path: path/to/output_model.gguf
    output_format: gguf
    quantization: q4
    model_type: auto
    device: auto
  - model_path: path/to/input_model2.bin
    output_path: path/to/output_model2.onnx
    output_format: onnx
    model_type: bert
    device: cpu