models:
  distilbert_onnx_simplify:
    input: "hf:distilbert-base-uncased"
    output_format: "onnx"
    output_path: "outputs/distilbert_onnx_simplify"
    model_type: "text-classification"
    postprocess: "simplify"
  distilbert_ts_optimize:
    input: "hf:distilbert-base-uncased"
    output_format: "torchscript"
    output_path: "outputs/distilbert_ts_optimize"
    model_type: "text-classification"
    postprocess: "optimize"
  distilbert_fp16_prune:
    input: "hf:distilbert-base-uncased"
    output_format: "fp16"
    output_path: "outputs/distilbert_fp16_prune"
    model_type: "text-classification"
    postprocess: "prune" 