name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install core dependencies (including torch)
        run: |
          pip install --no-cache-dir torch>=2.0.0 transformers>=4.30.0 tokenizers>=0.13.0 accelerate>=0.20.0

      - name: Install remaining dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Install model_converter_tool package
        run: |
          pip install -e .

      - name: Run all tests
        run: |
          pytest --maxfail=1 --disable-warnings -v
