name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install core dependencies
        run: |
          pip install -r requirements.txt

      - name: Install model_converter_tool package
        run: |
          pip install -e .

      - name: Run all tests
        run: |
          pytest --maxfail=1 --disable-warnings -v
