name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Cache pip dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Cache HuggingFace models
      - name: Cache HuggingFace models
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: ${{ runner.os }}-hf-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-hf-

      # Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Upgrade pip and install build tools
      - name: Upgrade pip and build tools
        run: python -m pip install --upgrade pip setuptools wheel

      # Install core dependencies
      - name: Install core dependencies
        run: pip install --no-cache-dir torch>=2.0.0 transformers>=4.30.0 tokenizers>=0.13.0 accelerate>=0.20.0

      # Install remaining dependencies
      - name: Install requirements.txt
        run: pip install --no-cache-dir -U -r requirements.txt

      # Install package in editable mode
      - name: Install model_converter_tool (editable)
        run: pip install -e .

      # Install llama.cpp Python dependencies
      - name: Install llama.cpp dependencies
        run: pip install --no-cache-dir -r tools/llama.cpp/requirements.txt

      # Run all unit and CLI tests (exclude integration)
      - name: Run unit and CLI tests
        run: pytest --maxfail=1 --disable-warnings -v -k "not test_integration"

  integration:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Cache pip dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Cache HuggingFace models
      - name: Cache HuggingFace models
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: ${{ runner.os }}-hf-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-hf-

      # Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Upgrade pip and install build tools
      - name: Upgrade pip and build tools
        run: python -m pip install --upgrade pip setuptools wheel

      # Install core dependencies
      - name: Install core dependencies
        run: pip install --no-cache-dir torch>=2.0.0 transformers>=4.30.0 tokenizers>=0.13.0 accelerate>=0.20.0

      # Install remaining dependencies
      - name: Install requirements.txt
        run: pip install --no-cache-dir -U -r requirements.txt

      # Install package in editable mode
      - name: Install model_converter_tool (editable)
        run: pip install -e .

      # Install llama.cpp Python dependencies
      - name: Install llama.cpp dependencies
        run: pip install --no-cache-dir -r tools/llama.cpp/requirements.txt

      # Run integration test only
      - name: Run integration test
        run: pytest --maxfail=1 --disable-warnings -v tests/test_integration.py
