name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install torch
        run: |
          pip install torch>=2.7.1

      - name: Verify torch installation
        run: |
          python -c "import torch; print(torch.__version__)"
        
      - name: Install other dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Run all tests
        run: pytest --maxfail=1 --disable-warnings -v
