name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Step 1: Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 2: Install system dependencies (for PyTorch and other libraries)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libopenblas-dev libomp-dev

      # Step 3: Set up virtual environment
      - name: Set up virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install --no-cache-dir torch==2.7.1
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir -e .

      # Step 4: Verify PyTorch installation
      - name: Verify torch installation
        run: |
          source venv/bin/activate
          python -c "import torch; print('Torch version:', torch.__version__)"

      # Step 5: Run all tests
      - name: Run all tests
        run: |
          source venv/bin/activate
          pytest --maxfail=1 --disable-warnings -v
