name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install torch first
        run: |
          pip install --no-cache-dir torch>=2.0.0

      - name: Install all other dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir -r llama.cpp/requirements.txt
          pip install -e .
          pip install typer

      - name: Check llama.cpp/convert_hf_to_gguf.py exists
        run: |
          test -f llama.cpp/convert_hf_to_gguf.py || (echo "convert_hf_to_gguf.py missing!" && exit 1)

      - name: Check gguf source directory exists
        run: |
          test -d llama.cpp/gguf-py/gguf || (echo "llama.cpp/gguf-py/gguf/ directory missing!" && exit 1)

      - name: GGUF conversion smoke test (Qwen2-0.5B)
        run: |
          python -m model_converter_tool.cli convert Qwen/Qwen2-0.5B --output ./outputs/qwen2-0.5B.gguf --to gguf --model-type qwen
          test -f ./outputs/qwen2-0.5B.gguf || (echo "GGUF conversion failed!" && exit 1)

      - name: Run all tests
        run: |
          pytest --maxfail=1 --disable-warnings -v
