name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install all dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt -U

      - name: Install model_converter_tool package
        run: |
          pip install -e .

      - name: Install llama.cpp Python dependencies
        run: |
          pip install --no-cache-dir -r llama.cpp/requirements.txt

      - name: Check convert_hf_to_gguf.py exists
        run: |
          test -f llama.cpp/convert_hf_to_gguf.py || (echo "convert_hf_to_gguf.py missing!" && exit 1)

      - name: Check gguf source directory exists
        run: |
          test -d llama.cpp/gguf-py/gguf || (echo "llama.cpp/gguf-py/gguf/ directory missing!" && exit 1)

      - name: Run all tests
        run: |
          pytest --maxfail=1 --disable-warnings -v
